### ISSUE TITLE
csrf질문

### ISSUE THREAD

**Issue by a4073631** [dev-Lesser/sinmungo-crawl-ray#1]
detail_url을 post할때 403에러가 발생되는데
헤더의 쿠키 설정은 했는데 csrf설정을 뭘 보고 해야 할지 모르겠습니다.
url 세션의 쿠키를 확인해도 csrf 토큰이 조회가 안되네요...

**Comment by dev-Lesser** [comment]
@a4073631 오래되어서 저도 가물가물하지만, 정부 기관 사이트 특성상, 유지보수만 하고 새롭게 추가되지는 않았다고 생각하고 작성 드리겠습니다.
2가지 확인 방법이 있습니다.

# 1. Network 탭에서 Request 확인
- 기본적으로 개발자도구의 Network 탭과, Application > Cookies 로 확인 가능하실텐데
- 질문 주신 detail_url 의 경우, Network 탭에서 확인해 보시면
**/nep/pttn/gnrlPttn/pttnSmlrCaseList.npaid** 로 POST 요청이 들어가는 것을 보실 수 있을 겁니다
- pttnSmlrCaseList.npaid 로 검색하시면 됩니다.

<img width="836" alt="image" src="https://github.com/dev-Lesser/sinmungo-crawl-ray/assets/83331402/4eee2596-97df-40ab-b5cf-545b63d630fd">

해당 Request 에 payload 에 _csrf 값이 있습니다.

<img width="389" alt="image" src="https://github.com/dev-Lesser/sinmungo-crawl-ray/assets/83331402/fb9d91e2-1885-482c-9b9f-4f4dfd61ed36">

# 2. 개발자도구 Element 탭에서 _csrf <meta tag> 확인
<img width="445" alt="image" src="https://github.com/dev-Lesser/sinmungo-crawl-ray/assets/83331402/6ac6504c-e933-4356-b83e-74e51dee8c9f">

- 기본적으로 html 파일 안에도 들어 있는 것도 확인 가능합니다~

**Comment by a4073631** [comment]
빠른 답변 감사합니다. 
접속은 알려주신대로 했는데  page 변수 값 때문에 index out문제가 생겨서 확인중입니다.
답변 감사합니다!
